server:
  port: 8763
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.4.201:18083
    sentinel:
          transport:
            port: 8719
            dashboard: 192.168.4.201:18085

feign.sentinel.enabled: true